[general]
token = ""
owner_id = 0
prefix = ","

[osu]
client_id = 0
client_secret = ""

[blacklists]
blacklisted_servers = []
blacklisted_dms = []

[channels]
error_reporting_channel = 0
event_poll_channel = 0
