"""add betting system

Revision ID: 0d6ce9e2e4e1
Revises: cb6068c9ff22
Create Date: 2026-02-12 22:06:16.449117

"""

# disable black for generated scripts
# fmt: off
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6ce9e2e4e1'
down_revision: Union[str, None] = 'cb6068c9ff22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bet_entries',
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('option_id', 'user_id')
    )
    op.create_table('bet_options',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('index'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bet_state',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('message_id', 'channel_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bet_state')
    op.drop_table('bet_options')
    op.drop_table('bet_entries')
    # ### end Alembic commands ###


# fmt: on
