"""add achievements

Revision ID: 1f8324d95ce2
Revises: bae610f6cec1
Create Date: 2025-07-19 18:41:43.904326

"""

# disable black for generated scripts
# fmt: off
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f8324d95ce2'
down_revision: Union[str, None] = 'bae610f6cec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_achievements',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('achievement_id', sa.String(), nullable=False),
        sa.Column('achieved', sa.Boolean(), nullable=False, default=False),
        sa.Column('progress', sa.Integer(), nullable=False, default=0),
        sa.Column('achieved_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('user_id', 'achievement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_achievements')
    # ### end Alembic commands ###


# fmt: on
