"""new persistent event poll system

Revision ID: 3e821400d673
Revises: 7c5bb40227ae
Create Date: 2025-09-23 18:16:31.423743

"""

# disable black for generated scripts
# fmt: off
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e821400d673'
down_revision: Union[str, None] = '7c5bb40227ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_bonus',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bonus', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('event_entry',
    sa.Column('entry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('entry_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('event_multipliers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=False),
    sa.Column('voted_for_winner', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    op.create_table('event_poll_state',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('end_timestamp', sa.DateTime(), nullable=False),
    sa.Column('warn_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_poll_state')
    op.drop_table('event_multipliers')
    op.drop_table('event_entry')
    op.drop_table('event_bonus')
    # ### end Alembic commands ###


# fmt: on
