"""config system

Revision ID: 43b84ad11d26
Revises: 3397fac93b9e
Create Date: 2025-09-22 19:41:59.264499

"""

# disable black for generated scripts
# fmt: off
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b84ad11d26'
down_revision: Union[str, None] = '3397fac93b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runtime_config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.PickleType(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.drop_column('guild_settings', 'last_train')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_settings', sa.Column('last_train', sa.INTEGER(), nullable=True))
    op.drop_table('runtime_config')
    # ### end Alembic commands ###


# fmt: on
