"""markov channel fix

Revision ID: 47568b411bb7
Revises: 43b84ad11d26
Create Date: 2025-09-22 14:34:31.205088

"""

# disable black for generated scripts
# fmt: off
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47568b411bb7'
down_revision: Union[str, None] = '43b84ad11d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_settings',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('markov_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.drop_table('guild_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_settings',
    sa.Column('guild_id', sa.INTEGER(), nullable=False),
    sa.Column('markov_enabled', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.drop_table('channel_settings')
    # ### end Alembic commands ###


# fmt: on
