"""default model

Revision ID: 4ecfd82a61f0
Revises:
Create Date: 2025-05-29 12:22:28.587473

"""

# disable black for generated scripts
# fmt: off
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ecfd82a61f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('fire',
    sa.Column('num', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reacts', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fb_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('attachments', sa.String(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('fb_msg_id', sa.Integer(), nullable=True),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('history',
    sa.Column('num', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_index(op.f('ix_history_user_id'), 'history', ['user_id'], unique=False)
    op.create_table('ignore',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('channelID', sa.Integer(), nullable=False),
    sa.Column('guildID', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('main',
    sa.Column('num', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('balance', sa.String(), nullable=False),
    sa.Column('bananas', sa.Integer(), nullable=False),
    sa.Column('user_ID', sa.Integer(), nullable=False),
    sa.Column('immunity', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('inventory', sa.String(), nullable=True),
    sa.Column('winloss', sa.String(), nullable=True),
    sa.Column('invested', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_index(op.f('ix_main_user_ID'), 'main', ['user_ID'], unique=True)
    op.create_table('messages',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('messageID', sa.Integer(), nullable=False),
    sa.Column('channelID', sa.Integer(), nullable=False),
    sa.Column('guildID', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('misc',
    sa.Column('num', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pointer', sa.String(), nullable=False),
    sa.Column('data', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('osu',
    sa.Column('num', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('osu_user', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('osu_users',
    sa.Column('num', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('osu_username', sa.String(), nullable=False),
    sa.Column('osu_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('poll_state',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('options', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('prestiege',
    sa.Column('num', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pres1', sa.Integer(), nullable=True),
    sa.Column('pres2', sa.Integer(), nullable=True),
    sa.Column('pres3', sa.Integer(), nullable=True),
    sa.Column('pres4', sa.Integer(), nullable=True),
    sa.Column('pres5', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_index(op.f('ix_prestiege_user_id'), 'prestiege', ['user_id'], unique=True)
    op.create_table('stocks',
    sa.Column('num', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_index(op.f('ix_stocks_user_id'), 'stocks', ['user_id'], unique=True)
    op.create_table('vote_multipliers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote_multipliers')
    op.drop_index(op.f('ix_stocks_user_id'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_prestiege_user_id'), table_name='prestiege')
    op.drop_table('prestiege')
    op.drop_table('poll_state')
    op.drop_table('osu_users')
    op.drop_table('osu')
    op.drop_table('misc')
    op.drop_table('messages')
    op.drop_index(op.f('ix_main_user_ID'), table_name='main')
    op.drop_table('main')
    op.drop_table('ignore')
    op.drop_index(op.f('ix_history_user_id'), table_name='history')
    op.drop_table('history')
    op.drop_table('fire')
    op.drop_table('blacklist')
    # ### end Alembic commands ###


# fmt: on
