"""fix int limit on stocks

Revision ID: 70d2a767ff4d
Revises: 3e821400d673
Create Date: 2025-10-31 15:13:33.122024

"""

# disable black for generated scripts
# fmt: off
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70d2a767ff4d'
down_revision: Union[str, None] = '3e821400d673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stocks", recreate="always") as batch:
            batch.alter_column(
                "amount",
                existing_type=sa.Integer(),
                type_=sa.Text(),          # use Text/String; SQLite ignores length anyway
                existing_nullable=False,
            )
    op.execute(sa.text("UPDATE stocks SET amount = CAST(amount AS TEXT)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stocks", recreate="always") as batch:
            batch.alter_column(
                "amount",
                existing_type=sa.Text(),
                type_=sa.Integer(),
                existing_nullable=False,
            )
    op.execute(sa.text("UPDATE stocks SET amount = CAST(amount AS INTEGER)"))
    # ### end Alembic commands ###


# fmt: on
