"""add nominations table

Revision ID: 7ac61d060175
Revises: b7d9e2f4a1c8
Create Date: 2026-07-03 18:25:38.695503

"""

# disable black for generated scripts
# fmt: off
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ac61d060175'
down_revision: Union[str, None] = 'b7d9e2f4a1c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nominations',
    sa.Column('num', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('half', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('num')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nominations')
    # ### end Alembic commands ###


# fmt: on
