"""remove old poll system

Revision ID: 7c5bb40227ae
Revises: 47568b411bb7
Create Date: 2025-09-23 18:15:48.616526

"""

# disable black for generated scripts
# fmt: off
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c5bb40227ae'
down_revision: Union[str, None] = '47568b411bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll_state')
    op.drop_table('bonuses')
    op.drop_table('vote_multipliers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote_multipliers',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('event_id', sa.INTEGER(), nullable=False),
    sa.Column('attended', sa.BOOLEAN(), nullable=False),
    sa.Column('voted_for_winner', sa.BOOLEAN(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    op.create_table('bonuses',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('bonus', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('poll_state',
    sa.Column('message_id', sa.INTEGER(), nullable=False),
    sa.Column('options', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


# fmt: on
