"""extended protection opt-in

Revision ID: 9a1f2c7de4b3
Revises: 7ac61d060175
Create Date: 2026-07-27 00:00:00.000000

"""

# disable black for generated scripts
# fmt: off
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a1f2c7de4b3'
down_revision: Union[str, None] = '7ac61d060175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("main",
    sa.Column("extended_protection", sa.Boolean(), server_default=sa.text("0"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("main", "extended_protection")
    # ### end Alembic commands ###


# fmt: on
