"""add awards db

Revision ID: b278c6800d6a
Revises: 70d2a767ff4d
Create Date: 2025-12-24 01:17:14.446947

"""

# disable black for generated scripts
# fmt: off
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b278c6800d6a'
down_revision: Union[str, None] = '70d2a767ff4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('award_users',
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('award_users')
    # ### end Alembic commands ###


# fmt: on
