"""new poll

Revision ID: bae610f6cec1
Revises: 4ecfd82a61f0
Create Date: 2025-06-27 03:56:51.457912

"""

# disable black for generated scripts
# fmt: off
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae610f6cec1'
down_revision: Union[str, None] = '4ecfd82a61f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote_multipliers')
    op.create_table('vote_multipliers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=False),
    sa.Column('voted_for_winner', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    op.create_table('bonuses',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bonus', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote_multipliers')
    op.create_table('vote_multipliers',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('multiplier', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('bonuses')
    # ### end Alembic commands ###


# fmt: on
