"""add api keys

Revision ID: c1006e6f6d5d
Revises: 1f8324d95ce2
Create Date: 2025-09-03 14:19:21.434324

"""

# disable black for generated scripts
# fmt: off
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1006e6f6d5d'
down_revision: Union[str, None] = '1f8324d95ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("api_keys",
    sa.Column("api_key", sa.String(length=255), nullable=False, primary_key=True),
    sa.Column("can_write", sa.Boolean(), nullable=False)
    )
    op.add_column("main",
    sa.Column("api_consent", sa.Boolean(), server_default=sa.text("0"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("api_keys")
    op.drop_column("main", "api_consent")
    # ### end Alembic commands ###


# fmt: on
