"""add voting

Revision ID: cb6068c9ff22
Revises: b278c6800d6a
Create Date: 2026-01-02 19:52:10.651058

"""

# disable black for generated scripts
# fmt: off
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb6068c9ff22'
down_revision: Union[str, None] = 'b278c6800d6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'voting',
        sa.Column('num', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('question', sa.Integer(), nullable=False),
        sa.Column('answer', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('num')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voting')
    # ### end Alembic commands ###


# fmt: on
