"""markov

Revision ID: d084ddbee31f
Revises: c1006e6f6d5d
Create Date: 2025-09-21 03:18:42.316298

"""

# disable black for generated scripts
# fmt: off
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd084ddbee31f'
down_revision: Union[str, None] = 'c1006e6f6d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_settings',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('markov_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_train', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('markov_corpus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('markov_corpus')
    op.drop_table('guild_settings')
    # ### end Alembic commands ###


# fmt: on
